//! Asserts `--format json|yaml` output is byte-identical to checked-in goldens.
//!
//! The review-mode pipeline (Phase 1+) extends `ast.Node` with new columns and
//! adds new parsers; these goldens guard against any regression that bleeds
//! through into the existing renderers. The pair of inputs is fixed in the
//! test bodies — the goldens are regenerated by re-running the CLI exactly the
//! way Task 0.3 / Step 1 documents.
//!
//! Pipeline mirrors `src/main.zig::diffOnePair`:
//!     parse → diff → suppressCascade → sortByLocation → renderJson|Yaml
//! Filtering is intentionally skipped (default = no filter, matches the CLI
//! invocation that produced the goldens).

const std = @import("std");
const Io = std.Io;
const syndiff = @import("syndiff");

const Format = enum { json, yaml };

fn diffPairToString(
    gpa: std.mem.Allocator,
    a_src: []const u8,
    b_src: []const u8,
    a_path: []const u8,
    b_path: []const u8,
    out: *Io.Writer.Allocating,
    format: Format,
) !void {
    var a = try syndiff.json_parser.parse(gpa, a_src, a_path);
    defer a.deinit();
    var b = try syndiff.json_parser.parse(gpa, b_src, b_path);
    defer b.deinit();

    var set = try syndiff.differ.diff(gpa, &a, &b);
    defer set.deinit(gpa);
    try syndiff.differ.suppressCascade(&set, &a, &b, gpa);
    syndiff.differ.sortByLocation(&set, &a, &b);

    switch (format) {
        .json => try syndiff.differ.renderJson(&set, &a, &b, &out.writer),
        .yaml => try syndiff.differ.renderYaml(&set, &a, &b, &out.writer),
    }
}

/// Read a checked-in golden under cwd; caller frees.
fn readGolden(gpa: std.mem.Allocator, io: Io, path: []const u8) ![]u8 {
    const cwd = Io.Dir.cwd();
    return cwd.readFileAlloc(io, path, gpa, .limited(1 << 16));
}

test "golden: json output for modified+added fields is byte-stable" {
    const gpa = std.testing.allocator;
    const io = std.testing.io;

    const a_src = "{\"name\":\"alice\",\"age\":30}\n";
    const b_src = "{\"name\":\"alice\",\"age\":31,\"new_field\":true}\n";

    var aw: Io.Writer.Allocating = .init(gpa);
    defer aw.deinit();
    try diffPairToString(gpa, a_src, b_src, "/tmp/a.json", "/tmp/b.json", &aw, .json);

    const golden = try readGolden(gpa, io, "testdata/golden/json_modified.golden");
    defer gpa.free(golden);

    try std.testing.expectEqualStrings(golden, aw.writer.buffered());
}

test "golden: yaml output for modified+added fields is byte-stable" {
    const gpa = std.testing.allocator;
    const io = std.testing.io;

    const a_src = "{\"name\":\"alice\",\"age\":30}\n";
    const b_src = "{\"name\":\"alice\",\"age\":31,\"new_field\":true}\n";

    var aw: Io.Writer.Allocating = .init(gpa);
    defer aw.deinit();
    try diffPairToString(gpa, a_src, b_src, "/tmp/a.json", "/tmp/b.json", &aw, .yaml);

    const golden = try readGolden(gpa, io, "testdata/golden/yaml_modified.golden");
    defer gpa.free(golden);

    try std.testing.expectEqualStrings(golden, aw.writer.buffered());
}
